name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN_FOR_LOWLIGHTER_METRICS }}
          template: terminal
          base: header, activity, community, repositories  # metadata
          plugin_languages: yes
          # plugin_languages_ignored: html, css
          # config_padding: 0, -1%
